language: node_js
node_js:
- '5'
- '4'
script: npm run ci
before_deploy: npm run build
deploy:
  provider: npm
  email: andrew.schrauf@gmail.com
  api_key:
    secure: WY0AR/Uri0hXYbFPJlbEnl6YfDmiDr0n9aFS3iG1C27Zr3MKmjb/iVft0USaHpNGSTrmEoyhP/nbT+ItoIkEn0wowCcgVpq39cu8Scop8fDvAfHFWc2e5x2Wq6JJV7KEpn/wCZRNP7fywTIpo5pTRIJD9OYNZxjDcs9NF1XQHId+0chocGmUoVacpecCe2o7vGyXh3G50l2qwJZhm73vOf5v/uuw8NqjNAvOU/D3GGjp2oBf9qk5IJfsPPCpDoSGQDoi7SbNNgcxNEKdCZsgV03MNcr9yXEg32iBIEGJ3iUPPuV8KWCCcBhXRS2QZJX0SmLDXUamhzfXKYd+7xD1HCsl9/sO6hvTW/S2zCV+Zw3hwF/6Y93u2NnRKmgNNWps8R5fYPv4rpMuLD+4ez3gkFKfkkMp6yw2vQft2HC0gw4phkPxL+Wt9yQ7UoRMrJJbsj/tD3SwpUGUGUJJyAzrfJVev1uwuNgac4cJGTkF9NbgVnZ4+9X/6D4Nj5Ua5SpqESdVwUnHwwILQJLKAuHRQS4yAf/CZQsxmvPZSlmh6goaYxyAAoxd2yz21/euwC4mwLNb3BqU42e8ekl9cUOhAbSsqYgwbRxKk5BWzyLa+9wVxb8aaXblC+wciiMi7LavH8aO3u8OYmCm3ob/A56xKHONCKaYDNf3zHlQmu/gs6s=
  on:
    tags: true
    repo: drewschrauf/acid-plugin-blog
